### ISSUE TITLE
Peer to Peer code Review

### ISSUE THREAD

**Issue by barakadanny** [Elijahdre/Awesome-books-es6#2]
Good job so far 🤝 , the project was well designed according to the initial design requested, and all the functionalities were implemented, Meanwhile, there is small adjustment that we think could improve the platform.

# Issues 📑 

- [ ] Responsiveness (The platform is not responsive on mobile devices)

Happy coding 🥂

**Comment by Elijahdre** [comment]
Hi @barakadanny Thanks for the review 👍. Change has been implemented. Have a great day.😁
